services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
#      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/logviewer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
      - elasticsearch
#    volumes:
#      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_PORT=3000
      - VITE_API_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/app  # Add volume for live reload
      - /app/node_modules  # Prevent overwriting node_modules
    command: npm run dev  # Override to run dev server
    depends_on:
      - backend
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app-network

  kibana:
    image: kibana:9.1.4
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: logviewer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  elasticsearch-data:
    driver: local
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge