services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    environment:
      - VITE_PORT=3000
      - VITE_API_URL=http://localhost:8080/api
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    depends_on:
      - backend
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app-network

#  kibana:
#    image: kibana:9.1.4
#    ports:
#      - "5601:5601"
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    depends_on:
#      - elasticsearch
#    networks:
#      - app-network

volumes:
  elasticsearch-data:
    driver: local

networks:
  app-network:
    driver: bridge