spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://elasticsearch:9200
    connection-timeout: 10s
    socket-timeout: 30s

logging:
  level:
    # Application packages - set to DEBUG for development
    ru.konkurst1.ekb.terraform_logviewer: DEBUG
    # Spring framework - set to INFO to avoid too much noise
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.data: INFO
    # Database - set to DEBUG to see SQL queries
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # Elasticsearch
    org.elasticsearch: INFO
    org.springframework.data.elasticsearch: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log

# Application Specific Configuration
#app:
#  log-parser:
#    # Maximum lines to parse in single file upload
#    max-lines: 10000
#    # Default page size for log entries
#    default-page-size: 50
#    # Supported timestamp formats
#    timestamp-formats:
#      - "yyyy-MM-dd HH:mm:ss"
#      - "HH:mm:ss"
#      - "yyyy-MM-dd'T'HH:mm:ss"
#
#  # CORS configuration for frontend
#  cors:
#    allowed-origins: "http://localhost:3000,http://localhost:5173"
#    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
#    allowed-headers: "*"
#    allow-credentials: true
#
## Management endpoints (for monitoring)
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics
#  endpoint:
#    health:
#      show-details: always
#    metrics:
#      enabled: true

# Spring Profiles
#---
#spring:
#  config:
#    activate:
#      on-profile: docker
#
#  datasource:
#    url: jdbc:postgresql://db:5432/logviewer
#  elasticsearch:
#    uris: http://elasticsearch:9200
#
#logging:
#  level:
#    ru.konkurst1.ekb.terraform_logviewer: INFO
#
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#logging:
#  level:
#    ru.konkurst1.ekb.terraform_logviewer: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#
#logging:
#  level:
#    ru.konkurst1.ekb.terraform_logviewer: INFO
#    org.springframework: WARN
#    org.hibernate.SQL: WARN