spring:
  datasource:
    url: jdbc:postgresql://db:5432/logviewer
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://elasticsearch:9200
    connection-timeout: 10s
    socket-timeout: 30s