server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://db:5432/logviewer
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true